models/category.py
from typing import Any

from other.validations import validate_non_empty_string, validate_string

category_name_validate_fun = {
    "true": validate_string, "": validate_non_empty_string}


class Category:
    def __init__(self, **kwargs: Any) -> None:
        self.__category_id = kwargs.get('category_id', "0")
        self.__category_name = category_name_validate_fun[kwargs.get('category_name_can_empty', "")](
            kwargs.get('category_name', ''), "Category Name")

    def is_modify(self):
        return (isinstance(self.category_id, int) and self.category_id > 0) or int(self.category_id) > 0

    @property
    def category_id(self):
        return self.__category_id

    @property
    def category_name(self):
        return self.__category_name

models/damage_loss.py
from typing import Any

from other.validations import *


class DamageLoss:
    def __init__(self, **kwargs: Any) -> None:
        self.__damage_loss_id = kwargs.get("damage_loss_id", "0")
        self.__voucher_no = validate_voucher_no(kwargs.get("voucher_no", ''))
        self.__tran_date = validate_trans_date(kwargs.get("tran_date", ''))
        self.__total_items = validate_number(
            kwargs.get("total_items", "0"), "Total items")
        self.__user_id = validate_number_greater_than_zero(
            kwargs.get("user_id", "0"), "User ID")

    def to_tuple_db(self):
        return (self.voucher_no, self.tran_date, self.total_items, self.user_id, self.damage_loss_id)

    def to_tuple_db_without_id(self):
        return (self.voucher_no, self.tran_date, self.total_items, self.user_id)

    @property
    def damage_loss_id(self):
        return self.__damage_loss_id

    @property
    def voucher_no(self):
        return self.__voucher_no

    @property
    def tran_date(self):
        return self.__tran_date

    @property
    def total_items(self):
        return self.__total_items

    @property
    def user_id(self):
        return self.__user_id

models/item.py
from typing import Any
from models.category import Category
from other.validations import *


class Item:
    def __init__(self,  **kwargs: Any) -> None:
        self.__item_id = kwargs.get('item_id', "0")
        self.__product_code = validate_code(
            kwargs.get('product_code', ''), "Product Code")
        self.__name = validate_non_empty_string(
            kwargs.get('name', ''), "Item Name")
        self.__price = validate_price(kwargs.get('price', '0'))
        self.__reorder = validate_number(
            kwargs.get('reorder', '0'), "Re-order Limit")
        self.__category = Category(**kwargs)
        self.__cost_price = kwargs.get('cost_price', '')

    def is_modify(self):
        return (isinstance(self.item_id, int) and self.item_id > 0) or int(self.item_id) > 0

    @property
    def item_id(self):
        return self.__item_id

    @property
    def product_code(self):
        return self.__product_code

    @property
    def name(self):
        return self.__name

    @property
    def price(self):
        return self.__price

    @property
    def reorder(self):
        return self.__reorder

    @property
    def category(self):
        return self.__category

    @property
    def category_id(self):
        return self.__category.category_id

    @property
    def category_name(self):
        return self.__category.category_name

    @property
    def cost_price(self):
        return self.__cost_price

controllers/category_controller.py
from typing import Any

from database.category_db import CategoryDatabase
from models.category import Category
from models.search_filter import SearchFilter


class CategoryController:
    def __init__(self):
        self.__database = CategoryDatabase()

# add, modify, delete

    def add_or_modify(self, category_dict: dict[str, Any]) -> str:
        category = Category(**category_dict)
        if category.is_modify():
            response = self.__database.modify(category)
        else:
            response = self.__database.add(category)
        return response

    def delete(self, id: int) -> str:
        response = self.__database.delete(id)
        return response

# Views

    def view(self, params: dict[str, Any]):
        search_filter = SearchFilter(**params)
        response = self.__database.view(search_filter)
        return response

    def get_all(self):
        response = self.__database.get_all()
        return response

controllers/item_controller.py
from typing import Any

from database.item_db import ItemDatabase
from database.user_role_permission_db import UserRolePermissionDatabase
from models.item import Item
from models.search_filter import SearchFilter


class ItemController:
    def __init__(self) -> None:
        self.__database = ItemDatabase()
        self.__user_role_permission_db = UserRolePermissionDatabase()

    # add, modify, delete
    def add_or_modify(self, item_dict: dict[str, Any]):
        item = Item(**item_dict)
        if item.is_modify():
            response = self.__database.modify(item)
        else:
            response = self.__database.add(item)
        return response

    def delete(self, item_id: int) -> str:
        response = self.__database.delete(item_id)
        return response

    # Views
    def view(self, params: dict[str, Any]):
        search_filter = SearchFilter(**params)
        response = self.__database.view(search_filter)
        return response

    def get_by_product_code(self, product_code: str):
        response = self.__database.get_by_product_code(product_code)
        return response

controllers/item_receive_controller.py
from models.search_filter import SearchFilter
from models.item_receive_detail import ItemReceiveDetail
from models.item_receive import ItemReceive
from database.item_receive_db import ItemReceiveDatabase
from typing import Any
from other.helper import to_list_tuple


class ItemReceiveController:
    def __init__(self):
        self.__database = ItemReceiveDatabase()

    def __get_details(self, details_list: list[dict[str, Any]]) -> list[ItemReceiveDetail]:
        details: list[ItemReceiveDetail] = []
        for detail_dict in details_list:
            detail = ItemReceiveDetail(**detail_dict)
            details.append(detail)
        return details

    def add(self, item_receive_dict: dict[str, Any]):
        item_receive = ItemReceive(**item_receive_dict)
        details = self.__get_details(item_receive_dict['details'])
        response = self.__database.add(item_receive, details)
        return response

    def modify(self, item_receive_dict: dict[str, Any]):
        item_receive = ItemReceive(**item_receive_dict)
        details = self.__get_details(item_receive_dict['details'])
        response = self.__database.modify(
            item_receive, details, to_list_tuple(item_receive_dict['delete_ids']))
        return response

    def delete(self, id: int):
        response = self.__database.delete(id)
        return response

    def view(self, params: dict[str, Any]):
        search_filter = SearchFilter(**params)
        response = self.__database.view(search_filter)
        return response

    def view_details(self, id: int):
        response = self.__database.view_details(id)
        return response

routes/inventory_routes.py
import json
from flask import Blueprint, jsonify, render_template, request, session
from controllers.damage_loss_controller import DamageLossController
from controllers.item_controller import ItemController
from controllers.category_controller import CategoryController
from controllers.item_receive_controller import ItemReceiveController
from controllers.user_role_permission_controller import UserRolePermissionController
from other.decorators import login_required

inventory_bp = Blueprint('inventory', __name__)
item_controller = ItemController()
category_controller = CategoryController()
item_receive_controller = ItemReceiveController()
damage_loss_controller = DamageLossController()
user_role_permission_controller = UserRolePermissionController()


#   Redirecting
@inventory_bp.route('/inventory/item')
@login_required
def get_inventory_item():
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'item_read'):
            return render_template('403.html')
        response = category_controller.get_all()
        return render_template('inventory/item.html', categories=response)
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@inventory_bp.route('/inventory/category')
@login_required
def get_inventory_category():
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'category_read'):
            return render_template('403.html')
        return render_template('inventory/category.html')
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@inventory_bp.route('/inventory/item-receive')
@login_required
def get_inventory_item_receive():
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'item_receive_read'):
            return render_template('403.html')
        return render_template('inventory/item_receive.html')
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@inventory_bp.route('/inventory/item-receive-voucher')
@login_required
def get_inventory_item_receive_voucher():
    try:
        return render_template('inventory/item_receive_voucher.html', user_id_session=session['user_data'][0])
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@inventory_bp.route('/inventory/damage-loss')
@login_required
def get_inventory_damage_loss():
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'damage_loss_read'):
            return render_template('403.html')
        return render_template('inventory/damage_loss.html')
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@inventory_bp.route('/inventory/damage-loss-voucher')
@login_required
def get_inventory_damage_loss_voucher():
    try:
        return render_template('inventory/damage_loss_voucher.html', user_id_session=session['user_data'][0])
    except Exception as e:
        return jsonify({'error': str(e)}), 400

# ---------- Start Item ----------
# Item List & Search Item function


@inventory_bp.route('/inventory/get-items', methods=['GET'])
@login_required
def get_items():
    try:
        params = request.args.to_dict()
        response = item_controller.view(params)
        return jsonify({"data": response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


# Add Edit items function
@inventory_bp.route('/inventory/add-edit-item', methods=['POST'])
@login_required
def add_edit_item():
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'item_write'):
            return jsonify({'error': 'You don\'t have permission to use this feature.'}), 403
        item_data = json.loads(request.data)
        response = item_controller.add_or_modify(item_data)
        return jsonify({'message': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400

# Delete Item function


@inventory_bp.route('/inventory/delete-item/<int:item_id>', methods=['DELETE'])
@login_required
def delete_item(item_id: int):
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'item_delete'):
            return jsonify({'error': 'You don\'t have permission to use this feature.'}), 403
        response = item_controller.delete(item_id)
        return jsonify({'message': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


# ---------- End Item ----------


# ---------- Start Category ----------
# category List & Search category function
@inventory_bp.route('/inventory/get-categories', methods=['GET'])
@login_required
def get_categories():
    try:
        params = request.args.to_dict()
        categories = category_controller.view(params)
        return jsonify({'data': categories}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


# Add Edit category function
@inventory_bp.route('/inventory/add-edit-category', methods=['POST'])
@login_required
def add_edit_category():
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'category_write'):
            return jsonify({'error': 'You don\'t have permission to use this feature.'}), 403
        category_data = json.loads(request.data)
        response = category_controller.add_or_modify(category_data)
        return jsonify({'message': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


# Delete Category function
@inventory_bp.route('/inventory/delete-category/<int:category_id>',
                    methods=['DELETE'])
@login_required
def delete_category(category_id: int):
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'category_delete'):
            return jsonify({'error': 'You don\'t have permission to use this feature.'}), 403
        response = category_controller.delete(category_id)
        return jsonify({'message': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


# ---------- End Category ----------


# ---------- Item Receive ----------
@inventory_bp.route('/inventory/get-receive-items', methods=['GET'])
@login_required
def get_receive_items():
    try:
        params = request.args.to_dict()
        response = item_receive_controller.view(params)
        return jsonify({'data': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


# Get Item Receive Details
@inventory_bp.route('/inventory/get-receive-item-details/<int:item_receive_id>')
@login_required
def get_receive_item_detail(item_receive_id: int):
    try:
        response = item_receive_controller.view_details(item_receive_id)
        return jsonify({'data': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


# Item Receive Voucher With Data
@inventory_bp.route('/inventory/item-receive-voucher/<voucher_no>')
@login_required
def get_inventory_item_receive_voucher_data(voucher_no: str):
    try:
        params = {'search_keyword': voucher_no}
        item_receive_response = item_receive_controller.view(params)
        if len(item_receive_response) > 0:
            item_receive_id = item_receive_response[0].get('item_receive_id')
            response_detail = item_receive_controller.view_details(
                item_receive_id)
            return render_template('inventory/item_receive_voucher.html',
                                   item_receive=item_receive_response,
                                   details=response_detail,
                                   user_id_session=session['user_data'][0],
                                   editing=True)
        return render_template('500.html')
    except Exception as e:
        return jsonify({'error': str(e)}), 400

# Delete Item Receive function


@inventory_bp.route('/inventory/delete-receive-item/<int:item_receive_id>',
                    methods=['DELETE'])
@login_required
def delete_receive_item(item_receive_id: int):
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'item_receive_delete'):
            return jsonify({'error': 'You don\'t have permission to use this feature.'}), 403
        response = item_receive_controller.delete(item_receive_id)
        return jsonify({'message': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@inventory_bp.route('/inventory/save_item_receive_voucher', methods=['POST'])
@login_required
def save_item_receive_voucher():
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'item_receive_write'):
            return jsonify({'error': 'You don\'t have permission to use this feature.'}), 403
        item_receive = request.get_json()
        response = item_receive_controller.add(item_receive)
        return jsonify({'message': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@inventory_bp.route('/inventory/update-item-receive-voucher', methods=['POST'])
@login_required
def update_item_receive_voucher():
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'item_receive_write'):
            return jsonify({'error': 'You don\'t have permission to use this feature.'}), 403
        item_receive = request.get_json()
        response = item_receive_controller.modify(item_receive)
        return jsonify({'message': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@inventory_bp.route('/inventory/get_item_by_product_code', methods=['GET'])
@login_required
def get_item_by_product_code():
    try:
        product_code = request.args.get('product_code', '')
        response = item_controller.get_by_product_code(product_code)
        return jsonify({'data': response}), 200

templates/inventory/category.html
{% extends 'layout/layout_setup.html' %}
{% block title %}Category{% endblock %}

{% block heading %}Category{% endblock %}

{% block form_title %}Add Category{% endblock %}
{% block hidden_id %}category_id{% endblock %}
{% block form_content %}
<div class="col-lg-6 col-12 form-floating mb-3 mx-auto ps-0">
    <input type="text" class="form-control" id="category_name" placeholder="Category Name" required />
    <label for="category_name"><i class="fab fa-product-hunt"></i>&nbsp;&nbsp; Category Name</label>
</div>

{% endblock %}

{% block list_title %}Category List{% endblock %}
{% block table_header %}
<tr>
    <th>No</th>
    <th>Category Name</th>
    <th>Action</th>
</tr>
{% endblock %}
{% block table_footer %}
<tr>
    <th>No</th>
    <th>Category Name</th>
    <th>Action</th>
</tr>
{% endblock %}
{% block table_body %}{% endblock %}

{% block js %}
<script type="module" src="{{ url_for('static', filename='js/category.js') }}"></script>{% endblock %}

templates/inventory/damage_loss.html
{% extends 'layout/layout_receive.html' %}
{% block title %}Damage/Loss{% endblock %}

{% block heading %}Damage/Loss{% endblock %}

{% block form_url %}{{ url_for('inventory.get_inventory_damage_loss_voucher') }}{% endblock %}
{% block form_id %}damage_loss_voucher{% endblock %}
{% block form_name %}Add Damage/Loss Voucher{% endblock %}

{% block list_title %}History{% endblock %}
{% block table_header %}
<tr>
    <th>No</th>
    <th>Voucher No</th>
    <th>Transaction Date</th>
    <th class="text-end">Total Items</th>
    <th>User Name</th>
    <th>Action</th>
</tr>
{% endblock %}
{% block table_footer %}
<tr>
    <th>No</th>
    <th>Voucher No</th>
    <th>Transaction Date</th>
    <th class="text-end">Total Items</th>
    <th>User Name</th>
    <th>Action</th>
</tr>
{% endblock %}
{% block table_body %}{% endblock %}
{% block detail_list_title %}Damage Loss Details {% endblock %}
{% block detail_table_header %}
<tr>
    <th>No</th>
    <th>Item Name</th>
    <th>Category</th>
    <th class="text-end">Price</th>
    <th class="text-end">Qty</th>
    <th class="text-end">Reorder Limit</th>
    <th>Remark</th>
</tr>
{% endblock %}
{% block detail_table_footer %}
<tr>
    <th>No</th>
    <th>Item Name</th>
    <th>Category</th>
    <th class="text-end">Price</th>
    <th class="text-end">Qty</th>
    <th class="text-end">Reorder Limit</th>
    <th>Remark</th>
</tr>
{% endblock %}
{% block detail_table_body %}{% endblock %}

{% block js %}
<script type="module" src="{{ url_for('static', filename='js/damage_loss.js') }}"></script>
<script src="{{ url_for('static', filename='js/datepicker.js') }}"></script>
{% endblock %}

templates/inventory/damage_loss_voucher.html
{% extends 'layout/layout_voucher.html' %}

{% block title %}
{% if editing %}
Edit Damage Loss Voucher
{% else %}
Damage Loss Voucher
{% endif %}
{% endblock %}

{% block hidden_id %}damage_loss_id{% endblock %}
{% block hidden_value %}{% if editing %}{{ damage_loss[0].damage_loss_id }}{% endif %}{% endblock %}

{% block hidden_login_user_id %}login_user_id{% endblock %}
{% block hidden_login_user_value %}{{user_id_session}}{% endblock %}

{% block form_event %}
{% if editing %}
onsubmit="updateDamageLossVoucher(event)"
{% else %}
onsubmit="saveDamageLossVoucher(event)"
{% endif %}
{% endblock %}

{% block back_url %}
{{ url_for('inventory.get_inventory_damage_loss') }}
{% endblock %}
{% block back_url_name %}
Damage/loss history
{% endblock %}

{% block voucher_no %}{% if editing %}{{ damage_loss[0].voucher_no }}{% endif %}{% endblock %}

{% block date %}{% if editing %}{{ damage_loss[0].tran_date }}{% endif %}{% endblock %}

{% block additional_form_content %}
<div class="col-md-11 mt-3 pe-4">
    <div>
        <textarea class="form-control me-5" id="remark" placeholder="Type to add remark" rows="3"></textarea>
    </div>
</div>
{% endblock %}

{% block table_header %}
<tr>
    <th>Code</th>
    <th colspan="4">Name</th>
    <th>Category</th>
    <th class="width-sm text-end">Qty</th>
    <th>Remark</th>
    <th></th>
</tr>
{% endblock %}
{% block table_body %}
{% if editing %}
{% for detail in details %}
<tr>
    <td>{{ detail.product_code }}</td>
    <td colspan="4">{{ detail.name }}</td>
    <td>{{ detail.category_name }}</td>
    <td><input type="number" class="form-control text-end" min="1" value="{{ detail.qty }}" pattern="[0-9]*"></td>
    <td hidden="true">{{ detail.item_id }}</td>
    <td hidden="true">{{ detail.damage_loss_details_id }}</td>
    <td>{{ detail.remark }}</td>
    <td class="text-center">
        <a class="delete" title="Delete" data-toggle="tooltip" type="button" onclick="removeItemFromTable(this)"><i
                class="fas fa-trash red-icon"></i></a>
    </td>
</tr>
{% endfor %}
{% endif %}
{% endblock %}

{% block total_items %}
{% if editing %}{{ damage_loss[0].total_items }}{% else %}0{% endif %}
{% endblock %}

{% block button %}
{% if not editing %}
<button class="btn btn-outline-secondary" type="button" onclick="clearAllInfo()">Cancel</button>
{% endif %}
<button class="btn btn-outline-success" type="submit" id="{% if editing %}update{% else %}save{% endif %}_voucher">
    {% if editing %}Update{% else %}Save{% endif %} Voucher
</button>
{% endblock %}

{% block js %}
<script src="{{ url_for('static', filename='js/damage_loss_voucher.js') }}"></script>{% endblock %}

templates/inventory/item.html
{% extends 'layout/layout_setup.html' %}
{% block title %}Item{% endblock %}

{% block heading %}Item{% endblock %}
{% block select_content %}
<div class="col-lg-4 col-sm-4 mb-3">
    <div class="input-group">
        <label class="input-group-text" for="categoryFilter"><i class="fa-solid fa-filter"></i></label>
        <select class="form-select" aria-label="Filter select" id="categoryFilter">
            <option value="" selected> All Categories</option>
            {% for category in categories %}
            <option value="{{ category.category_id }}">{{ category.category_name }}</option>
            {% endfor %}
        </select>
    </div>
</div>
{% endblock %}

{% block form_title %}Add Item{% endblock %}
{% block hidden_id %}item_id{% endblock %}
{% block form_content %}
<div class="col-12 col-xl-2 col-lg-4 col-sm-6 form-floating mb-3">
    <input type="text" class="form-control" id="name" placeholder="Item Name" required />
    <label for="name" class="ps-4"><i class="fas fa-cubes"></i>&nbsp;&nbsp; Item Name</label>
</div>
<div class="col-12 col-xl-2 col-lg-4 col-sm-6 form-floating mb-3">
    <input type="text" class="form-control" id="product_code" placeholder="Item Code" required />
    <label for="product_code" class="ps-4"><i class="fab fa-product-hunt"></i>&nbsp;&nbsp; Product Code</label>
</div>
<div class="col-12 col-xl-2 col-lg-4 col-sm-6 form-floating mb-3">
    <input type="number" class="form-control text-end" min="0" value=0 id="cost_price" pattern="[0-9]*"
        placeholder="Price" required />
    <label for="price" class="ps-4"><i class="fas fa-tags"></i>&nbsp;&nbsp; Cost Price</label>
</div>
<div class="col-12 col-xl-2 col-lg-4 col-sm-6 form-floating mb-3">
    <input type="number" class="form-control text-end" min="0" value=0 id="price" pattern="[0-9]*" placeholder="Price"
        required />
    <label for="price" class="ps-4"><i class="fas fa-tags"></i>&nbsp;&nbsp; Selling Price</label>
</div>
<div class="col-12 col-xl-2 col-lg-4 col-sm-6 form-floating mb-3">
    <input type="number" class="form-control text-end" min="0" value=0 id="reorder" pattern="[0-9]*"
        placeholder="Re-Order Limit" required />
    <label for="reorder" class="ps-4"><i class="fa-solid fa-retweet"></i>&nbsp;&nbsp; Re-Order Limit</label>
</div>
<div class="col-12 col-xl-2 col-lg-4 col-sm-6 form-floating mb-3">
    <select class="form-select" id="category_id" style="padding-top: inherit;" required>
        <option value="" selected>&#x29E9;-----Category-----</option>
        {% for category in categories %}
        <option value="{{ category.category_id }}">{{ category.category_name }}</option>
        {% endfor %}
    </select>
</div>
{% endblock %}

{% block list_title %}Item List{% endblock %}
{% block table_header %}
<tr>
    <th>No</th>
    <th>Name</th>
    <th>Product Code</th>
    <th class="text-end">Cost Price</th>
    <th class="text-end">Selling Price</th>
    <th class="text-end">Re-Order Limit</th>
    <th>Category</th>
    <th class="text-end">Current Stock</th>
    <th>Action</th>
</tr>
{% endblock %}
{% block table_footer %}
<tr>
    <th>No</th>
    <th>Name</th>
    <th>Product Code</th>
    <th class="text-end">Cost Price</th>
    <th class="text-end">Selling Price</th>
    <th class="text-end">Re-Order Limit</th>
    <th>Category</th>
    <th class="text-end">Current Stock</th>
    <th>Action</th>
</tr>
{% endblock %}
{% block table_body %}{% endblock %}


{% block js %}
<script type="module" src="{{ url_for('static', filename='js/item.js') }}"></script>{% endblock %}

templates/inventory/item_receive.html
{% extends 'layout/layout_receive.html' %}
{% block title %}Item Receive{% endblock %}

{% block heading %}Item Receive{% endblock %}

{% block form_url %}{{ url_for('inventory.get_inventory_item_receive_voucher') }}{% endblock %}
{% block form_id %}receive_voucher{% endblock %}
{% block form_name %}Add Receive Voucher{% endblock %}

{% block list_title %}History{% endblock %}
{% block table_header %}
<tr>
    <th>No</th>
    <th>Voucher No</th>
    <th>Transaction Date</th>
    <th class="text-end">Total Items</th>
    <th>User Name</th>
    <th>Action</th>
</tr>
{% endblock %}
{% block table_footer %}
<tr>
    <th>No</th>
    <th>Voucher No</th>
    <th>Transaction Date</th>
    <th class="text-end">Total Items</th>
    <th>User Name</th>
    <th>Action</th>
</tr>
{% endblock %}
{% block table_body %}{% endblock %}
{% block detail_list_title %}Item Receive Details {% endblock %}
{% block detail_table_header %}
<tr>
    <th>No</th>
    <th>Item Name</th>
    <th>Category</th>
    <th class="text-end">Cost Price</th>
    <th class="text-end">Qty</th>
    <th class="text-end">Reorder Limit</th>
</tr>
{% endblock %}
{% block detail_table_footer %}
<tr>
    <th>No</th>
    <th>Item Name</th>
    <th>Category</th>
    <th class="text-end">Cost Price</th>
    <th class="text-end">Qty</th>
    <th class="text-end">Reorder Limit</th>
</tr>
{% endblock %}
{% block detail_table_body %}{% endblock %}

{% block js %}
<script type="module" src="{{ url_for('static', filename='js/item_receive.js') }}"></script>
<script src="{{ url_for('static', filename='js/datepicker.js') }}"></script>
{% endblock %}

templates/inventory/item_receive_voucher.html
{% extends 'layout/layout_voucher.html' %}

{% block title %}
{% if editing %}
Edit Item Receive Voucher
{% else %}
Item Receive Voucher
{% endif %}
{% endblock %}

{% block hidden_id %}item_receive_id{% endblock %}
{% block hidden_value %}{% if editing %}{{ item_receive[0].item_receive_id }}{% endif %}{% endblock %}

{% block hidden_login_user_id %}login_user_id{% endblock %}
{% block hidden_login_user_value %}{{user_id_session}}{% endblock %}

{% block form_event %}
{% if editing %}
onsubmit="updateItemReceiveVoucher(event)"
{% else %}
onsubmit="saveItemReceiveVoucher(event)"
{% endif %}
{% endblock %}

{% block back_url %}
{{ url_for('inventory.get_inventory_item_receive') }}
{% endblock %}
{% block back_url_name %}
Item Receive History
{% endblock %}

{% block voucher_no %}{% if editing %}{{ item_receive[0].voucher_no }}{% endif %}{% endblock %}

{% block date %}{% if editing %}{{ item_receive[0].tran_date }}{% endif %}{% endblock %}

{% block table_header %}
<tr>
    <th>Code</th>
    <th colspan="4">Name</th>
    <th>Category</th>
    <th class="width-sm text-end">Qty</th>
    <th></th>
</tr>
{% endblock %}
{% block table_body %}
{% if editing %}
{% for detail in details %}
<tr>
    <td>{{ detail.product_code }}</td>
    <td colspan="4">{{ detail.name }}</td>
    <td>{{ detail.category_name }}</td>
    <td><input type="number" class="form-control text-end" min="1" value="{{ detail.qty }}" pattern="[0-9]*"></td>
    <td hidden="true">{{ detail.item_id }}</td>
    <td hidden="true">{{ detail.item_receive_details_id }}</td>
    <td class="text-center">
        <a class="delete" title="Delete" data-toggle="tooltip" type="button" onclick="removeItemFromTable(this)"><i
                class="fas fa-trash red-icon"></i></a>
    </td>
</tr>
{% endfor %}
{% endif %}
{% endblock %}

{% block total_items %}
{% if editing %}
{{ item_receive[0].total_items }}
{% else %}
0
{% endif %}
{% endblock %}

{% block button %}
{% if not editing %}
<button class="btn btn-outline-secondary" type="button" onclick="clearAllInfo()">Cancel</button>
{% endif %}
<button class="btn btn-outline-success" type="submit" id="{% if editing %}update{% else %}save{% endif %}_voucher">
    {% if editing %}Update{% else %}Save{% endif %} Voucher
</button>
{% endblock %}

{% block js %}
<script src="{{ url_for('static', filename='js/item_receive_voucher.js') }}"></script>
{% endblock %}