models/store_configuration.py
from typing import Any

from other.validations import *


class StoreConfiguration:

    def __init__(self, **kwargs: Any) -> None:
        self.__store_name = validate_non_empty_string(
            kwargs.get("store_name", ""), "Store name")
        self.__contact_person = kwargs.get("contact_person", "")
        self.__phone_no = validate_non_empty_string(
            kwargs.get("phone_no", ""), "Phone no")
        self.__address = validate_non_empty_string(
            kwargs.get("address", ""), "Address")
        self.__image_data = kwargs.get("image_data", b"")

    def to_tuple_db(self):
        return (self.store_name, self.contact_person, self.phone_no,
                self.address, self.image_data)

    def to_tuple_db_without_id(self):
        return (self.store_name, self.contact_person, self.phone_no,
                self.address, self.image_data)

    @property
    def store_name(self):
        return self.__store_name

    @property
    def contact_person(self):
        return self.__contact_person

    @property
    def phone_no(self):
        return self.__phone_no

    @property
    def address(self):
        return self.__address

    @property
    def image_data(self):
        return self.__image_data

controllers/store_configuration_controller.py
from typing import Any
from database.store_configuration_db import StoreConfigDatabase
from models.store_configuration import StoreConfiguration


class StoreConfigController:
    def __init__(self) -> None:
        self.__database = StoreConfigDatabase()

    def modify(self, store_config_dict: dict[str, Any]):
        store_config = StoreConfiguration(**store_config_dict)
        response = self.__database.modify(store_config)
        return response

    def view(self):
        response = self.__database.view()
        return response

    def get_image(self):
        response = self.__database.get_image()
        return response

routes/setting_routes.py
from io import BytesIO
import json
from flask import Blueprint, jsonify, render_template, request, send_file, session  # type: ignore
from controllers.store_configuration_controller import StoreConfigController
from controllers.user_controller import UserController
from controllers.user_role_controller import UserRoleController
from controllers.user_role_permission_controller import UserRolePermissionController
from other.decorators import login_required

setting_bp = Blueprint('setting', __name__)
# Create an instance of the User and UserList Controller
user_controller = UserController()
role_controller = UserRoleController()
user_role_permission_controller = UserRolePermissionController()
store_config_controller = StoreConfigController()

#   Redirecting


@setting_bp.route('/setting/user_management')
@login_required
def get_user_management():
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'users'):
            return render_template('403.html')
        response = role_controller.get_all()
        return render_template('setting/user_management.html', roles=response)
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@setting_bp.route('/setting/role_management')
@login_required
def get_role_management():
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'user_roles'):
            return render_template('403.html')
        return render_template('setting/role_management.html')
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@setting_bp.route('/setting/user_permission/<role_id>/<role_name>')
@login_required
def get_user_permission(role_id: int, role_name: str):
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'user_permissions'):
            return render_template('403.html')
        return render_template('setting/user_permission.html', role_id=role_id, role_name=role_name)
    except Exception as e:
        return jsonify({'error': str(e)}), 400


# ---------- Start Role ----------
# role List & Search role function
@setting_bp.route('/setting/get-roles', methods=['GET'])
@login_required
def get_roles():
    try:
        params = request.args.to_dict()
        response = role_controller.view(params)
        return jsonify({'data': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


# Add Edit Role function
@setting_bp.route('/setting/add-edit-role', methods=['POST'])
@login_required
def add_edit_roles():
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'user_roles'):
            return jsonify({'error': 'You don\'t have permission to use this feature.'}), 403
        role_data = json.loads(request.data)
        response = role_controller.add_or_modify(role_data)
        return jsonify({'message': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


# Delete Role function
@setting_bp.route('/setting/delete-role/<int:role_id>',
                  methods=['DELETE'])
@login_required
def delete_role(role_id: int):
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'user_roles'):
            return jsonify({'error': 'You don\'t have permission to use this feature.'}), 403
        response = role_controller.delete(role_id)
        return jsonify({'message': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400

# ---------- End Role ----------


# ---------- Start User ----------
# Users List & Search User function
@setting_bp.route('/setting/get-users', methods=['GET'])
@login_required
def get_users():
    try:
        params = request.args.to_dict()
        response = user_controller.view(params)
        return jsonify({'data': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400

# Add Edit Users function


@setting_bp.route('/setting/add-edit-user', methods=['POST'])
@login_required
def add_edit_user():
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'users'):
            return jsonify({'error': 'You don\'t have permission to use this feature.'}), 403
        user_data = json.loads(request.data)
        response = user_controller.add_or_modify(user_data)
        return jsonify({'message': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400

# Delete user function


@setting_bp.route('/setting/delete-user/<int:user_id>', methods=['DELETE'])
@login_required
def delete_user(user_id: int):
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'users'):
            return jsonify({'error': 'You don\'t have permission to use this feature.'}), 403
        response = user_controller.delete(user_id)
        return jsonify({'message': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


# ---------- End Item ----------

# Store Configuration
@setting_bp.route('/setting/save_store_configuration', methods=['GET', 'POST'])
@login_required
def save_store_config():
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'store_configuration'):
            return render_template('403.html')
        if request.method == 'POST':
            store_name = request.form['storename']
            contact_person = request.form['contactperson']
            phone_no = request.form['phonenumber']
            address = request.form['address']
            file = request.files['file']
            response = store_config_controller.modify(
                {'store_name': store_name, 'contact_person': contact_person, 'phone_no': phone_no, 'address': address, 'image_data': file.read()})
            return jsonify({'message': response}), 200
        return render_template('setting/store_configuration.html')
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@setting_bp.route('/setting/get_store_image', methods=['GET'])
@login_required
def get_store_image():
    try:
        response = store_config_controller.get_image()
        if response:
            image_stream = BytesIO(response)
            return send_file(image_stream, mimetype='image/jpeg')
    except Exception as e:
        return jsonify({'error': str(e)}), 404


@setting_bp.route('/setting/get_store_configuration', methods=['GET'])
@login_required
def get_store_configuration():
    try:
        response = store_config_controller.view()
        return jsonify({'data': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


# ---------- End Store Configuration ----------


# User Permissoin
@setting_bp.route('/setting/save_user_permission', methods=['POST'])
@login_required
def save_user_permission():
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'user_permissions'):
            return jsonify({'error': 'You don\'t have permission to use this feature.'}), 403
        permissions = json.loads(request.data)
        response = user_role_permission_controller.modify(permissions)
        return jsonify({'message': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@setting_bp.route('/setting/load_user_permission/<int:role_id>', methods=['GET'])
@login_required
def load_user_permission(role_id: int):
    try:
        response = user_role_permission_controller.get_by_role_id(role_id)
        return jsonify({'data': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400
# ---------- End User Permissoin ----------

templates/setting/role_management.html
{% extends 'layout/layout_setup.html' %}
{% block title %}User Roles{% endblock %}

{% block heading %}User Roles{% endblock %}

{% block form_title %}Add Role{% endblock %}
{% block hidden_id %}role_id{% endblock %}
{% block form_content %}
<div class="col-lg-6 col-12 form-floating mb-3 mx-auto ps-0">
    <input type="text" class="form-control" id="role_name" placeholder="Role Name" required />
    <label for="role_name" class="ps-4"><i class="fab fa-product-hunt"></i>&nbsp;&nbsp; Role Name</label>
</div>
{% endblock %}

{% block list_title %}User Roles List{% endblock %}
{% block table_header %}
<tr>
    <th>No</th>
    <th>Role Name</th>
    <th>Action</th>
</tr>
{% endblock %}
{% block table_footer %}
<tr>
    <th>No</th>
    <th>Role Name</th>
    <th>Action</th>
</tr>
{% endblock %}
{% block table_body %}{% endblock %}

{% block js %}
<script type="module" src="{{ url_for('static', filename='js/role.js') }}"></script>
{% endblock %}

templates/setting/store_configuration.html
{% extends 'layout/base.html' %}
<h1>{% block title %}Store Configuration{% endblock %}</h1>
{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/store_configuration.css') }}" />
{% endblock %}
{% block content %}
<div class="upload-store-data text-center">
    <div class="upload-store-data-frame">
        <form method="POST" enctype="multipart/form-data" id="formStore">
            <div class="upload-store-photo">
                <img id="logo_image">
                <div class="upload-photo-btn">
                    <input type="file" name="file">
                    <i class="fa-solid fa-camera" style="color: #ffffff;"></i>
                </div>
            </div>

            <div class="form-floating input-box mb-3">
                <input type="text" class="form-control" id="storename" name="storename" placeholder="Store Name"
                    required>
                <label for="storename">Store Name</label>
            </div>
            <div class="form-floating input-box mb-3">
                <input type="text" class="form-control" id="contactperson" name="contactperson"
                    placeholder="Contact Person" required>
                <label for="contactperson">Contact Person</label>
            </div>
            <div class="form-floating input-box mb-3">
                <input type="text" class="form-control" id="phonenumber" name="phonenumber" placeholder="Phone No."
                    required>
                <label for="phonenumber">Phone No.</label>
            </div>
            <div class="form-floating input-box mb-3">
                <input type="text" class="form-control" id="address" name="address" placeholder="Address" required>
                <label for="address">Address</label>
            </div>
            <div class="d-flex justify-content-center py-3">
                <button type="submit" class="btn btn-outline-success">Submit</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block js %}
<script src="{{ url_for('static', filename='js/store_configuration.js') }}"></script>
{% endblock %}

templates/setting/user_management.html
{% extends 'layout/layout_setup.html' %}
{% block title %}User{% endblock %}

{% block heading %}User{% endblock %}
{% block select_content %}
<div class="col-lg-4 col-sm-4 mb-3">
    <div class="input-group">
        <label class="input-group-text" for="roleFilter"><i class="fa-solid fa-filter"></i></label>
        <select class="form-select" aria-label="Filter select" id="roleFilter">
            <option value="" selected> All UserRoles</option>
            {% for role in roles %}
            <option value="{{ role.role_id }}">{{ role.role_name }}</option>
            {% endfor %}
        </select>
    </div>
</div>
{% endblock %}

{% block form_title %}Add User{% endblock %}
{% block hidden_id %}user_id{% endblock %}
{% block form_content %}
<div class="col-12 form-floating mb-3">
    <input type="text" class="form-control" id="username" placeholder="UserName" required />
    <label for="username" class="ps-4"><i class="fas fa-cubes"></i>&nbsp;&nbsp;
        UserName</label>
</div>
<div class="col form-floating mb-3">
    <input type="password" class="form-control" id="password" placeholder="password" required />
    <label for="password" class="ps-4"><i class="fab fa-product-hunt"></i>&nbsp;&nbsp;
        Password </label>
</div>
<div class="col form-floating mb-3">
    <select class="form-select" id="role_id" style="padding-top: inherit;" required>
        <option value="" selected>&#x29E9;-----User Roles-----</option>
        {% for role in roles %}
        <option value="{{ role.role_id }}">{{ role.role_name }}</option>
        {% endfor %}
    </select>
</div>
{% endblock %}

{% block list_title %}User List{% endblock %}
{% block table_header %}
<tr>
    <th>No</th>
    <th>UserName</th>
    <th>User Role</th>
    <th>Action</th>
</tr>
{% endblock %}
{% block table_footer %}
<tr>
    <th>No</th>
    <th>UserName</th>
    <th>User Role</th>
    <th>Action</th>
</tr>
{% endblock %}
{% block table_body %}{% endblock %}

{% block js %}
<script type="module" src="{{ url_for('static', filename='js/user.js') }}"></script>{% endblock %}

templates/setting/user_permission.html
{% extends 'layout/base.html' %}
{% block title %}UserRole Permission{% endblock %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/user_permission.css') }}" />
{% endblock %}

{% block content %}
<p class="fs-6 mb-3 color-peru">
    <a href="{{url_for('setting.get_role_management')}}">
        <i class="fas fa-angle-double-left me-3"></i>UserRole Management
    </a>
</p>

<input type="hidden" id="role_id" value="{{ role_id }}">
<form onsubmit="save_user_permission(event)">
    <div class="user_permission_page mt-4">
        <div class="card">
            <div class="card-body">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">{{role_name}} Role's Permissions</h6>
                </div>
                <div class="check-list">
                    <div class="row">
                        <div class="col col-lg-4"><b class="fs-6">Item</b></div>
                        <div class="col"><label>Read</label>
                            <input class="checkbox" type="checkbox" id="item_read">
                        </div>
                        <div class="col"><label>Write</label>
                            <input class="checkbox" type="checkbox" id="item_write">
                        </div>
                        <div class="col"><label>Delete</label>
                            <input class="checkbox" type="checkbox" id="item_delete">
                        </div>
                    </div>
                </div>
                <div class="check-list">
                    <div class="row">
                        <div class="col col-lg-4"><b class="fs-6">Category</b></div>
                        <div class="col"><label>Read</label>
                            <input class="checkbox" type="checkbox" id="category_read">
                        </div>
                        <div class="col"><label>Write</label>
                            <input class="checkbox" type="checkbox" id="category_write">
                        </div>
                        <div class="col"><label>Delete</label>
                            <input class="checkbox" type="checkbox" id="category_delete">
                        </div>
                    </div>
                </div>
                <div class="check-list">
                    <div class="row">
                        <div class="col col-lg-4"><b class="fs-6">Item Receive</b></div>
                        <div class="col"><label>Read</label>
                            <input class="checkbox" type="checkbox" id="item_receive_read">
                        </div>
                        <div class="col"><label>Write</label>
                            <input class="checkbox" type="checkbox" id="item_receive_write">
                        </div>
                        <div class="col"><label>Delete</label>
                            <input class="checkbox" type="checkbox" id="item_receive_delete">
                        </div>
                    </div>
                </div>
                <div class="check-list">
                    <div class="row">
                        <div class="col col-lg-4"><b class="fs-6">Damage/Loss</b></div>
                        <div class="col"><label>Read</label>
                            <input class="checkbox" type="checkbox" id="damage_loss_read">
                        </div>
                        <div class="col"><label>Write</label>
                            <input class="checkbox" type="checkbox" id="damage_loss_write">
                        </div>
                        <div class="col"><label>Delete</label>
                            <input class="checkbox" type="checkbox" id="damage_loss_delete">
                        </div>
                    </div>
                </div>
                <div class="check-list">
                    <div class="row">
                        <div class="col col-lg-4"><b class="fs-6">Sales</b></div>
                        <div class="col"><label>Read</label>
                            <input class="checkbox" type="checkbox" id="sales_read">
                        </div>
                        <div class="col"><label>Write</label>
                            <input class="checkbox" type="checkbox" id="sales_write">
                        </div>
                        <div class="col"><label>Delete</label>
                            <input class="checkbox" type="checkbox" id="sales_delete">
                        </div>
                    </div>
                </div>
                <div class="check-list">
                    <div class="row">
                        <div class="col col-lg-4"><b class="fs-6">Reports</b></div>
                        <div class="col"><label>All</label>
                            <input class="checkbox" type="checkbox" id="reports">
                        </div>
                    </div>
                </div>
                <div class="check-list">
                    <div class="row">
                        <div class="col col-lg-4"><b class="fs-6">User Management</b></div>
                        <div class="col"><label>All</label>
                            <input class="checkbox" type="checkbox" id="users">
                        </div>
                    </div>
                </div>
                <div class="check-list">
                    <div class="row">
                        <div class="col col-lg-4"><b class="fs-6">UserRole Management</b></div>
                        <div class="col"><label>All</label>
                            <input class="checkbox" type="checkbox" id="user_roles">
                        </div>
                    </div>
                </div>
                <div class="check-list">
                    <div class="row">
                        <div class="col col-lg-4"><b class="fs-6">UserRole Permissions</b></div>
                        <div class="col"><label>All</label>
                            <input class="checkbox" type="checkbox" id="user_permissions">
                        </div>
                    </div>
                </div>
                <div class="check-list">
                    <div class="row">
                        <div class="col col-lg-4"><b class="fs-6">Store Configuration</b></div>
                        <div class="col"><label>All</label>
                            <input class="checkbox" type="checkbox" id="store_configuration">
                        </div>
                    </div>
                </div>
                <div class="text-center mb-3">
                    <button type="submit pt-3" class="btn btn-outline-success">Save</button>
                </div>
            </div>
        </div>
    </div>
</form>

<script src="{{ url_for('static', filename='js/user_permission.js') }}"></script>
{% endblock %}