models/sale.py
from typing import Any

from other.validations import *


class Sale:

    def __init__(self, **kwargs: Any) -> None:
        self.__sale_id = kwargs.get("sale_id", "0")
        self.__voucher_no = validate_voucher_no(kwargs.get("voucher_no", ""))
        self.__tran_date = validate_trans_date(kwargs.get("tran_date", ""))
        self.__total_items = validate_number(
            kwargs.get("total_items", "0"), "Total items")
        self.__user_id = validate_number_greater_than_zero(
            kwargs.get("user_id", "0"), "User ID")
        self.__discount = validate_number(
            kwargs.get("discount", "0.0"), "Discount")
        self.__total_amount = validate_number(
            kwargs.get("total_amount", "0.0"), "Total amount")
        self.__discount_percentage = validate_number(
            kwargs.get("discount_percentage", "0"), "Discount Percentage")
        self.__payment = kwargs.get("payment", "")

    def to_tuple_db(self):
        return (self.voucher_no, self.tran_date, self.total_items,
                self.user_id, self.discount, self.total_amount, self.discount_percentage, self.payment, self.sale_id)

    def to_tuple_db_without_id(self):
        return (self.voucher_no, self.tran_date, self.total_items,
                self.user_id, self.discount, self.total_amount, self.discount_percentage, self.payment)

    @property
    def sale_id(self):
        return self.__sale_id

    @property
    def voucher_no(self):
        return self.__voucher_no

    @property
    def tran_date(self):
        return self.__tran_date

    @property
    def total_items(self):
        return self.__total_items

    @property
    def user_id(self):
        return self.__user_id

    @property
    def discount(self):
        return self.__discount

    @property
    def total_amount(self):
        return self.__total_amount

    @property
    def discount_percentage(self):
        return self.__discount_percentage

    @property
    def payment(self):
        return self.__payment

controllers/sale_controller.py
from typing import Any
from models.sale import Sale
from models.sale_detail import SaleDetail
from database.sale_db import SaleDatabase
from models.search_filter import SearchFilter
from other.helper import to_list_tuple


class SaleController:
    def __init__(self):
        self.__database = SaleDatabase()

    def __get_details(self, details_list: list[dict[str, Any]]) -> list[SaleDetail]:
        details: list[SaleDetail] = []
        for detail_dict in details_list:
            detail = SaleDetail(**detail_dict)
            details.append(detail)
        return details

    def add(self, sale_dict: dict[str, Any]):
        sale = Sale(**sale_dict)
        details = self.__get_details(sale_dict['details'])
        response = self.__database.add(sale, details)
        return response

    def modify(self, sale_dict: dict[str, Any]):
        sale = Sale(**sale_dict)
        details = self.__get_details(sale_dict['details'])
        response = self.__database.modify(
            sale, details, to_list_tuple(sale_dict['delete_ids']))
        return response

    def delete(self, id: int):
        response = self.__database.delete(id)
        return response

    def view(self, params: dict[str, Any]):
        search_filter = SearchFilter(**params)
        response = self.__database.view(search_filter)
        return response

    def view_details(self, id: int):
        response = self.__database.view_details(id)
        return response

routes/sale_routes.py
from flask import Blueprint, jsonify, render_template, request, session
from controllers.sale_controller import SaleController
from controllers.user_role_permission_controller import UserRolePermissionController
from other.decorators import login_required


sale_bp = Blueprint('sale', __name__)
sale_controller = SaleController()
user_role_permission_controller = UserRolePermissionController()


@sale_bp.route('/sale')
@login_required
def sale():
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'sales_read'):
            return render_template('403.html')
        return render_template('sale/sale.html')
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@sale_bp.route('/sale/sale-voucher')
@login_required
def get_sale_voucher():
    try:
        return render_template('sale/sale_voucher.html', user_id_session=session['user_data'][0])
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@sale_bp.route('/sale/get-sale', methods=['GET'])
@login_required
def get_sale():
    try:
        params = request.args.to_dict()
        response = sale_controller.view(params)
        return jsonify({"data": response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@sale_bp.route('/sale/get-sale-details/<int:sale_id>')
@login_required
def get_sale_detail(sale_id: int):
    try:
        response = sale_controller.view_details(sale_id)
        return jsonify({"data": response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@sale_bp.route('/sale/sale-voucher/<voucher_no>')
@login_required
def get_sale_voucher_data(voucher_no: str):
    params = {
        'from_tran_date': '',
        'to_tran_date': '',
        'search_keyword': voucher_no,
        'page_no': 1,
    }
    sale_response = sale_controller.view(params)
    if sale_response:
        if sale_response is not None and len(sale_response) > 0:
            sale_id = sale_response[0].get('sale_id')
            sale_detail_response = sale_controller.view_details(sale_id)
            payment = sale_response[0].get('payment')
            crdp, cshp, dgtp = "", "", ""
            payment_type = {}
            if payment == "crdp":
                crdp = "Selected"
            elif payment == "cshp":
                cshp = "Selected"
            elif payment == "dgtp":
                dgtp = "Selected"
            payment_type = {'crdp': crdp, 'cshp': cshp, 'dgtp': dgtp}
            return render_template('sale/sale_voucher.html',
                                   sale=sale_response,
                                   details=sale_detail_response,
                                   payment_type=payment_type,
                                   user_id_session=session['user_data'][0],
                                   editing=True)
    return render_template('500.html')


@sale_bp.route('/sale/delete-sale/<int:sale_id>',
               methods=['DELETE'])
@login_required
def delete_sale(sale_id: int):
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'sales_delete'):
            return jsonify({'error': 'You don\'t have permission to use this feature.'}), 403
        response = sale_controller.delete(sale_id)
        return jsonify({"message": response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@sale_bp.route('/sale/save_sale_voucher', methods=['POST'])
@login_required
def save_sale_voucher():
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'sales_write'):
            return jsonify({'error': 'You don\'t have permission to use this feature.'}), 403
        sale = request.get_json()
        response = sale_controller.add(sale)
        return jsonify({"message": response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@sale_bp.route('/sale/update-sale-voucher', methods=['POST'])
@login_required
def update_sale_voucher():
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'sales_write'):
            return jsonify({'error': 'You don\'t have permission to use this feature.'}), 403
        sale = request.get_json()
        response = sale_controller.modify(sale)
        return jsonify({"message": response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400

templates/sale/sale.html
{% extends 'layout/layout_receive.html' %}
{% block title %}Sale{% endblock %}

{% block heading %}Sale{% endblock %}

{% block form_url %}{{ url_for('sale.get_sale_voucher') }}{% endblock %}
{% block form_id %}sales_voucher{% endblock %}
{% block form_name %}Add Sale Voucher{% endblock %}

{% block list_title %}History{% endblock %}
{% block table_header %}
<tr>
  <th>No</th>
  <th>Voucher No</th>
  <th>Transaction Date</th>
  <th class="text-end">Total Items</th>
  <th class="text-end">Discount</th>
  <th class="text-end">Total Amount</th>
  <th>Payment</th>
  <th>User Name</th>
  <th>Action</th>
</tr>
{% endblock %}
{% block table_footer %}
<tr>
  <th>No</th>
  <th>Voucher No</th>
  <th>Transaction Date</th>
  <th class="text-end">Total Items</th>
  <th class="text-end">Discount</th>
  <th class="text-end">Total Amount</th>
  <th>Payment</th>
  <th>User Name</th>
  <th>Action</th>
</tr>
{% endblock %}
{% block table_body %}{% endblock %}

{% block detail_list_title %}Sale Details {% endblock %}
{% block detail_table_header %}
<tr>
  <th>No</th>
  <th>Item Name</th>
  <th>Category</th>
  <th class="text-end">Sale Price</th>
  <th class="text-end">Qty</th>
  <th class="text-end">Reorder Limit</th>
</tr>
{% endblock %}
{% block detail_table_footer %}
<tr>
  <th>No</th>
  <th>Item Name</th>
  <th>Category</th>
  <th class="text-end">Price</th>
  <th class="text-end">Qty</th>
  <th class="text-end">Reorder Limit</th>
</tr>
{% endblock %}
{% block detail_table_body %}{% endblock %}

{% block js %}
<script type="module" src="{{ url_for('static', filename='js/sale.js') }}"></script>
<script src="{{ url_for('static', filename='js/datepicker.js') }}"></script>

{% endblock %}

templates/sale/sale_voucher.html
{% extends 'layout/layout_voucher.html' %}

{% block title %}
{% if editing %}
Edit Sale Voucher
{% else %}
Sale Voucher
{% endif %}
{% endblock %}

{% block hidden_id %}sale_id{% endblock %}
{% block hidden_value %}{% if editing %}{{ sale[0].sale_id }}{% endif %}{% endblock %}

{% block hidden_login_user_id %}login_user_id{% endblock %}
{% block hidden_login_user_value %}{{user_id_session}}{% endblock %}

{% block form_event %}
{% if editing %}
onsubmit="updateSaleVoucher(event)"
{% else %}
onsubmit="saveSaleVoucher(event)"
{% endif %}
{% endblock %}

{% block back_url %}
{{ url_for('sale.sale') }}
{% endblock %}
{% block back_url_name %}
Sale history
{% endblock %}

{% block voucher_no %}{% if editing %}{{ sale[0].voucher_no }}{% endif %}{% endblock %}

{% block date %}{% if editing %}{{ sale[0].tran_date }}{% endif %}{% endblock %}

{% block table_header %}
<tr>
    <th>Code</th>
    <th colspan="4">Name</th>
    <th>Category</th>
    <th class="text-end">Price</th>
    <th class="width-sm text-end">Qty</th>
    <th class="text-end">Total</th>
    <th></th>
</tr>
{% endblock %}
{% block table_body %}
{% if editing %}
{% for detail in details %}
<tr>
    <td>{{ detail.product_code }}</td>
    <td colspan="4">{{ detail.name }}</td>
    <td>{{ detail.category_name }}</td>
    <td class="text-end">{{ detail.price }}</td>
    <td><input type="number" class="form-control text-end" min="1" onkeyup="changeTotalsByQty(this)"
            onclick="changeTotalsByQty(this)" pattern="[0-9]*" value="{{ detail.qty }}"></td>
    <td class="width-sm text-end">{{ detail.price * detail.qty }}</td>
    <td hidden="true">{{ detail.item_id }}</td>
    <td hidden="true">{{ detail.sale_details_id }}</td>
    <td class="text-center">
        <a class="delete" title="Delete" data-toggle="tooltip" type="button" onclick="removeItemFromTable(this)"><i
                class="fas fa-trash red-icon"></i></a>
    </td>
</tr>
{% endfor %}
{% endif %}
{% endblock %}
{% block total_items %}
{% if editing %}{{ sale[0].total_items }}{% else %}0{% endif %}
{% endblock %}
{% block sub_total %}
<div class="row text-end p-3">
    <div class="col">
        <label>Sub-Total :</label>
        <input type="text" class="text-end" id="sub_total" disabled width="100px">
    </div>
</div>
<div class="row text-end p-3">
    <div class="col">
        <label>Discount (%) :</label>
        <input type="number" class="text-end" id="discount_percentage" pattern="[0-9]*"
            value="{% if editing %}{{ sale[0].discount_percentage }}{% else %}0{% endif %}"
            onchange="getDiscount(this.value)">
    </div>
</div>
<div class="row text-end p-3">
    <div class="col">
        <label>Discount :</label>
        <input type="text" class="text-end" id="discount" disabled>
    </div>
</div>
<div class="row text-end p-3">
    <div class="col">
        <label>Total :</label>
        <input type="text" class="text-end" disabled id="totals">
    </div>
</div>
<div class="row text-end p-3">
    <div class="col">
        <label>Payment Type :</label>
        <select class="form-select float-end ms-1 py-1" aria-label="Filter select" id="payment" style="width: 190px;"
            required>
            {% if editing %}
            <option value="crdp" {{ payment_type.crdp }}>Card Payment</option>
            <option value="cshp" {{ payment_type.cshp }}>Cash Payment</option>
            <option value="dgtp" {{ payment_type.dgtp }}>Digital Payment</option>
            {% else %}
            <option value="" selected disabled> ---- payment ---- </option>
            <option value="crdp">Card Payment</option>
            <option value="cshp">Cash Payment</option>
            <option value="dgtp">Digital Payment</option>
            {% endif %}
        </select>
    </div>
</div>
{% endblock %}

{% block button %}
{% if not editing %}
<button class="btn btn-outline-secondary" type="button" onclick="clearAllInfo()">Cancel</button>
{% endif %}
<button class="btn btn-outline-success" type="submit" id="{% if editing %}update{% else %}save{% endif %}_voucher">
    {% if editing %}Update{% else %}Save{% endif %} Voucher
</button>
{% endblock %}

{% block js %}
<script src="{{ url_for('static', filename='js/sale_voucher.js') }}"></script>
{% endblock %}