routes/reports_routes.py
from flask import Blueprint, jsonify, render_template, request, session
import json
from controllers.dashboard_controller import DashboardController
from controllers.inventory_report_controller import InventoryReportController
from controllers.sale_report_controller import SaleReportController
from controllers.user_role_permission_controller import UserRolePermissionController
from other.decorators import login_required

reports_bp = Blueprint('report', __name__)
sale_report_controller = SaleReportController()
inventory_report_controller = InventoryReportController()
dashboard_controller = DashboardController()
user_role_permission_controller = UserRolePermissionController()


@reports_bp.route('/report/sale')
@login_required
def get_sale_report():
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'reports'):
            return render_template('403.html')
        response = sale_report_controller.get_year()
        return render_template('report/sale_report.html', years=response)
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@reports_bp.route('/report/inventory')
@login_required
def get_inventory_report():
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'reports'):
            return render_template('403.html')
        return render_template('report/inventory_report.html')
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@reports_bp.route('/report/dashboard')
@login_required
def get_dashboard_report():
    try:
        return render_template('report/dashboard.html')
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@reports_bp.route('/report/get-top-selling', methods=['POST'])
@login_required
def get_top_selling():
    try:
        request_data = json.loads(request.data)
        from_date = request_data.get('fromDate')
        to_date = request_data.get('toDate')
        params = {
            'from_date': from_date,
            'to_date': to_date,
        }
        response = sale_report_controller.get_top_selling(params)
        return jsonify({'data': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@reports_bp.route('/report/get-items-qty-data', methods=['POST'])
@login_required
def get_items_by_total_sales():
    try:
        request_data = json.loads(request.data)
        from_date = request_data.get('fromDate')
        to_date = request_data.get('toDate')
        params = {
            'from_date': from_date,
            'to_date': to_date,
        }
        response = sale_report_controller.get_items_by_total_sales(params)
        return jsonify({'data': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@reports_bp.route('/report/get-total-sales-categories', methods=['POST'])
@login_required
def get_categories_sales_by_total_sales():
    try:
        request_data = json.loads(request.data)
        from_date = request_data.get('fromDate')
        to_date = request_data.get('toDate')
        params = {
            'from_date': from_date,
            'to_date': to_date,
        }
        response = sale_report_controller.get_categories_sales_by_total_sales(
            params)
        return jsonify({'data': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@reports_bp.route('/report/get-total-sales', methods=['POST'])
@login_required
def get_total_sales_by_month():
    try:
        sale = json.loads(request.data)
        option = sale.get('option')
        from_date = sale.get('fromDate')
        to_date = sale.get('toDate')
        params = {
            'option': option,
            'from_date': from_date,
            'to_date': to_date,
        }
        response = sale_report_controller.get_total_sales(params)
        return jsonify({'data': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@reports_bp.route('/report/get-sale-report-daily/<date>')
@login_required
def get_sale_report_by_daily(date: str):
    try:
        response = sale_report_controller.get_sale_report_by_daily(date)
        return jsonify({'data': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@reports_bp.route('/report/get-qty-category', methods=['POST'])
@login_required
def get_qty_sold_by_category():
    try:
        sale = json.loads(request.data)
        option = sale.get('option')
        from_date = sale.get('fromDate')
        to_date = sale.get('toDate')
        params = {
            'option': option,
            'from_date': from_date,
            'to_date': to_date,
        }
        response = sale_report_controller.get_qty_sold_by_category(params)
        return jsonify({'data': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@reports_bp.route('/report/get-revenue-category', methods=['POST'])
@login_required
def get_revenue_category():
    try:
        sale = json.loads(request.data)
        option = sale.get('option')
        from_date = sale.get('fromDate')
        to_date = sale.get('toDate')
        params = {
            'option': option,
            'from_date': from_date,
            'to_date': to_date,
        }
        response = sale_report_controller.get_revenue_category(params)
        return jsonify({'data': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@reports_bp.route('/report/get-qty-item', methods=['POST'])
@login_required
def get_qty_sold_by_item():
    try:
        request_data = json.loads(request.data)
        option = request_data.get('option')
        from_date = request_data.get('fromDate')
        to_date = request_data.get('toDate')
        params = {
            'option': option,
            'from_date': from_date,
            'to_date': to_date,
        }
        response = sale_report_controller.get_qty_sold_by_item(params)
        return jsonify({'data': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@reports_bp.route('/report/get-revenue-item', methods=['POST'])
@login_required
def get_revenue_item():
    try:
        request_data = json.loads(request.data)
        option = request_data.get('option')
        from_date = request_data.get('fromDate')
        to_date = request_data.get('toDate')
        params = {
            'option': option,
            'from_date': from_date,
            'to_date': to_date,
        }

        response = sale_report_controller.get_revenue_item(params)
        return jsonify({'data': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@reports_bp.route('/report/get-sale-growth', methods=['POST'])
@login_required
def get_sale_growth():
    try:
        request_data = json.loads(request.data)
        year = request_data.get('year')
        response = sale_report_controller.get_sale_growth(year)
        return jsonify({'data': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@reports_bp.route('/report/get-quarterly-sale', methods=['POST'])
@login_required
def get_quarterly_sale():
    try:
        request_data = json.loads(request.data)
        year = request_data.get('year')
        response = sale_report_controller.get_quarterly_sale(year)
        return jsonify({'data': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@reports_bp.route('/report/inventory-report-info', methods=['POST'])
@login_required
def get_inventory_report_info():
    try:
        year = request.args.get('year', '')
        response = inventory_report_controller.get_stock_info_by_year(year)
        return jsonify({'data': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@reports_bp.route('/report/monthly-inventory-info', methods=['POST'])
@login_required
def get_monthly_inventory_info():
    try:
        year = request.args.get('year', '')
        response = inventory_report_controller.get_stock_transactions_by_year(
            year)
        return jsonify({'data': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@reports_bp.route('/report/dashboard-sales-total', methods=['POST'])
@login_required
def get_dashboard_sales_total():
    try:
        response = dashboard_controller.sales()
        return jsonify({'data': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@reports_bp.route('/report/dashboard-inventory-info', methods=['POST'])
@login_required
def get_dashboard_inventory_info():
    try:
        response = dashboard_controller.inventory_info()
        return jsonify({'data': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@reports_bp.route('/report/dashboard-inventory-transactions', methods=['POST'])
@login_required
def get_dashboard_inventory_transactions():
    try:
        date = request.args.get('date', '')
        response = dashboard_controller.inventory_transactions(date)
        return jsonify({'data': response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400

routes/sale_routes.py
from flask import Blueprint, jsonify, render_template, request, session
from controllers.sale_controller import SaleController
from controllers.user_role_permission_controller import UserRolePermissionController
from other.decorators import login_required


sale_bp = Blueprint('sale', __name__)
sale_controller = SaleController()
user_role_permission_controller = UserRolePermissionController()


@sale_bp.route('/sale')
@login_required
def sale():
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'sales_read'):
            return render_template('403.html')
        return render_template('sale/sale.html')
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@sale_bp.route('/sale/sale-voucher')
@login_required
def get_sale_voucher():
    try:
        return render_template('sale/sale_voucher.html', user_id_session=session['user_data'][0])
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@sale_bp.route('/sale/get-sale', methods=['GET'])
@login_required
def get_sale():
    try:
        params = request.args.to_dict()
        response = sale_controller.view(params)
        return jsonify({"data": response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@sale_bp.route('/sale/get-sale-details/<int:sale_id>')
@login_required
def get_sale_detail(sale_id: int):
    try:
        response = sale_controller.view_details(sale_id)
        return jsonify({"data": response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@sale_bp.route('/sale/sale-voucher/<voucher_no>')
@login_required
def get_sale_voucher_data(voucher_no: str):
    params = {
        'from_tran_date': '',
        'to_tran_date': '',
        'search_keyword': voucher_no,
        'page_no': 1,
    }
    sale_response = sale_controller.view(params)
    if sale_response:
        if sale_response is not None and len(sale_response) > 0:
            sale_id = sale_response[0].get('sale_id')
            sale_detail_response = sale_controller.view_details(sale_id)
            payment = sale_response[0].get('payment')
            crdp, cshp, dgtp = "", "", ""
            payment_type = {}
            if payment == "crdp":
                crdp = "Selected"
            elif payment == "cshp":
                cshp = "Selected"
            elif payment == "dgtp":
                dgtp = "Selected"
            payment_type = {'crdp': crdp, 'cshp': cshp, 'dgtp': dgtp}
            return render_template('sale/sale_voucher.html',
                                   sale=sale_response,
                                   details=sale_detail_response,
                                   payment_type=payment_type,
                                   user_id_session=session['user_data'][0],
                                   editing=True)
    return render_template('500.html')


@sale_bp.route('/sale/delete-sale/<int:sale_id>',
               methods=['DELETE'])
@login_required
def delete_sale(sale_id: int):
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'sales_delete'):
            return jsonify({'error': 'You don\'t have permission to use this feature.'}), 403
        response = sale_controller.delete(sale_id)
        return jsonify({"message": response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@sale_bp.route('/sale/save_sale_voucher', methods=['POST'])
@login_required
def save_sale_voucher():
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'sales_write'):
            return jsonify({'error': 'You don\'t have permission to use this feature.'}), 403
        sale = request.get_json()
        response = sale_controller.add(sale)
        return jsonify({"message": response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400


@sale_bp.route('/sale/update-sale-voucher', methods=['POST'])
@login_required
def update_sale_voucher():
    try:
        if not user_role_permission_controller.has_permission(session['user_data'][-1], 'sales_write'):
            return jsonify({'error': 'You don\'t have permission to use this feature.'}), 403
        sale = request.get_json()
        response = sale_controller.modify(sale)
        return jsonify({"message": response}), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 400

templates/layout/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}POS{% endblock %}</title>
    {% include 'layout/head.html' %}
    {% block css %}
    {% endblock %}
</head>

<body>
    {% include 'layout/nav.html' %}
    <div class="content">
        <div class="container-fluid px-5">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    {% block js %}{% endblock %}
    <script src="{{ url_for('static', filename='js/logo.js') }}"></script>
</body>

</html>

templates/layout/base_layout.html
{% extends 'layout/base.html' %}

{% block content %}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{% block heading %}{% endblock %}</h1>
</div>
<!-- Search Form -->
<div class="row">
    <div class="col-xl-6 col-lg-10 col-md-12 mb-4">
        <div class="card border-left-primary shadow h-100">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col-xl-4 col-md-4 col-sm-4 searchLayout mb-3">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" id="search_input"
                                placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
                        </div>
                    </div>
                    {% block select_content %}{% endblock %}
                    <div class="col-auto mb-3">
                        <button class="btn btn-primary" type="button" id="searchButton">
                            <i class="fas fa-search fa-sm"></i>
                        </button>
                    </div>
                    <div class="col-auto mb-3">
                        <button class="btn btn-outline-secondary" type="button" id="resetSearchButton">CLEAR</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ======END Search Form======== -->
<!-- Add Form -->
{% block add_form_content %}{% endblock %}
<!-- List -->
<div class="row">
    <div class="col-12 mb-4">
        <div class="card shadow mb-4">
            <div class="card-header">
                <h6 class="m-0 font-weight-bold text-primary">{% block list_title %}{% endblock %}</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            {% block table_header %}{% endblock %}
                        </thead>
                        <tfoot>
                            {% block table_footer %}{% endblock %}
                        </tfoot>
                        <tbody>
                            {% block table_body %}{% endblock %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End List -->
{% block details_List_content %}{% endblock %}

{% endblock %}

templates/layout/head.html
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta charset="utf-8" />
  <link rel="shortcut icon" href="{{ url_for('static', filename='/img/pos_logo.ico') }}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.css" />

  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/nav.css') }}" />

  <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />

  <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css" />

  <!-- voucher datepicker css -->
  <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/vanillajs-datepicker@1.1.4/dist/css/datepicker.min.css'>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>

  <script src="https://code.jquery.com/jquery-3.6.0.js"></script>

  <!-- voucher datepicker js -->
  <script src='https://cdn.jsdelivr.net/npm/vanillajs-datepicker@1.1.4/dist/js/datepicker-full.min.js'></script>

  <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>

  <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>

  <script type="module" src="https://cdn.jsdelivr.net/npm/chart.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
</head>

templates/layout/layout_receive.html
{% extends 'layout/base_layout.html' %}

{% block select_content %}
<div class="col-xl-4 col-md-4 col-sm-4 mb-3">
    <div class="input-group">
        <input type="text" class="form-control fromDate" placeholder="From" aria-describedby="basic-addon2" id="from"
            name="from" />
        <span class="input-group-text btnFrom" id="basic-addon2"><i class="fa fa-calendar"></i></span>
    </div>
</div>
<div class="col-xl-4 col-md-4 col-sm-4 mb-3">
    <div class="input-group">
        <input type="text" class="form-control toDate" placeholder="To" aria-describedby="basic-addon2" id="to"
            name="to" />
        <span class="input-group-text btnTo" id="basic-addon2"><i class="fa fa-calendar"></i></span>
    </div>
</div>
{% endblock %}

{% block add_form_content %}
<div class="row justify-content-end mb-4">
    <div class="col-lg-3 col-sm-4 text-center">
        <a href="{% block form_url %}{% endblock %}" class="btn btn-primary" type="button"
            id="{% block form_id %}{% endblock %}">{% block form_name %}{% endblock %}</a>
    </div>
</div>
{% endblock %}
{% block details_List_content %}
<div class="row">
    <div class="col-12 mb-4">
        <div class="card shadow mb-4">
            <div class="card-header">
                <h6 class="m-0 font-weight-bold text-primary">{% block detail_list_title %}{% endblock %}<span
                        class="detail_voucher_no"></span></h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataDetailTable" width="100%" cellspacing="0">
                        <thead>
                            {% block detail_table_header %}
                            {% endblock %}
                        </thead>
                        <tfoot>
                            {% block detail_table_footer %}
                            {% endblock %}
                        </tfoot>
                        <tbody>
                            {% block detail_table_body %}{% endblock %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/layout/layout_setup.html
{% extends 'layout/base_layout.html' %}

{% block add_form_content %}
<div class="row">
    <div class="col-xl-12 col-md-12 mb-4">
        <div class="card border-left-primary shadow h-100">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <form id="form">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4" id="formTitle">{% block form_title %}{% endblock %}</h1>
                            <input type="hidden" id="{% block hidden_id %}{% endblock %}" value="">
                        </div>
                        <div class="row">
                            {% block form_content %}{% endblock %}
                            <div class="text-center">
                                <button type="submit" class="btn btn-outline-success">SUBMIT</button>
                                <input type="reset" class="btn btn-outline-secondary" id="btnClear" value="CLEAR">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/layout/layout_voucher.html
{% extends 'layout/base.html' %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/voucher.css') }}" />
{% endblock %}
{% block content %}

<input type="hidden" id="{% block hidden_id %}{% endblock %}" value="{% block hidden_value %}{% endblock %}">
<input type="hidden" id="{% block hidden_login_user_id %}{% endblock %}"
    value="{% block hidden_login_user_value %}{% endblock %}">
<form {% block form_event %}{% endblock %}>
    <div class="shadow p-3 mt-3 mb-5 rounded">
        <p class="fs-6 mb-3 color-peru">
            <a href="{% block back_url %}{% endblock %}">
                <i class="fas fa-angle-double-left me-3"></i>{% block back_url_name %}{% endblock %}
            </a>
        </p>
        <div class="row g-3 mb-3 mt-1">
            <div class="col-lg-2 col-sm-5 ms-3">
                <label for="voucherNo" class="form-label ms-3">Voucher No.</label>
                <input type="text" class="form-control" id="voucherNo" placeholder="eg. A0001" tabindex="1"
                    value="{% block voucher_no %}{% endblock %}" readonly>
            </div>
            <div class="col-lg-2 col-sm-4">
                <label for="date" class="form-label">Date</label>
                <input type="text" class="datepicker_input form-control" id="date" placeholder="yyyy-mm-dd" tabindex="2"
                    required value="{% block date %}{% endblock %}">
            </div>
        </div>

        <div class="col-lg-8 rounded-2 mb-3 p-3 ">
            <div class="row input-group">
                <div class="col-md-2 me-1">
                    <select class="form-select" id="selectBy">
                        <option selected value="code_no">Code No</option>
                    </select>
                </div>
                <input type="text" class="form-control col-md-7" placeholder="Type to add product" id="product_search"
                    tabindex="3">
                <div class="col-md-2">
                    <input type="number" class="form-control text-end" placeholder="Qty" min="1" value=1 id="qty"
                        pattern="[0-9]*" tabindex="4">
                </div>
                <button class="btn btn-primary col-md-1" type="button" id="add_item"
                    onclick="addItemToTable()">Add</button>
            </div>
            {% block additional_form_content %}{% endblock %}
        </div>

        <div table-responsive>
            <table class="table table-borderless table-striped table-hover table-fixed align-middle" id="item_table">
                <thead>
                    {% block table_header %}{% endblock %}
                </thead>
                <tbody id="item_table_body">
                    {% block table_body %}{% endblock %}
                </tbody>
            </table>
        </div>

        <div id="liveAlertPlaceholder"></div>
        <div class="card">
            <div class="card-body text-end">
                <div class="row">
                    <div class="col-lg-11">
                        <p>Total item(s) :</p>
                    </div>
                    <div class="col-lg-1 pe-3">
                        <b id="total_item_count">{% block total_items %}{% endblock %}</b>
                    </div>
                </div>
            </div>
            {% block sub_total %}{% endblock %}
        </div>

        <div class="text-end mt-4">
            {% block button %}
            {% endblock %}
        </div>
    </div>
</form>

{% endblock %}

templates/layout/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<div class="container-fluid">
		<a class="navbar-brand" href="item">
			<img id="image" width="80" height="40">
		</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
			aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0 py-3">
				<li class="nav-item px-3">
					<a class="nav-link" aria-current="page" href="{{url_for('report.get_dashboard_report')}}">HOME</a>
				</li>
				<li class="nav-item dropdown px-3">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
						data-bs-toggle="dropdown" aria-expanded="false">INVENTORY</a>
					<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
						<li><a class="dropdown-item" href="{{url_for('inventory.get_inventory_item')}}">Item</a></li>
						<li><a class="dropdown-item" href="{{url_for('inventory.get_inventory_category')}}">Category</a>
						</li>
						<li><a class="dropdown-item" href="{{url_for('inventory.get_inventory_item_receive')}}">Item
								Receive</a></li>
						<li><a class="dropdown-item"
								href="{{url_for('inventory.get_inventory_damage_loss')}}">Damage/Loss</a></li>
					</ul>
				</li>
				<li class="nav-item px-3">
					<a class="nav-link" aria-current="page" href="{{url_for('sale.sale')}}">SALE</a>
				</li>
				<li class="nav-item dropdown px-3">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
						data-bs-toggle="dropdown" aria-expanded="false">REPORTS</a>
					<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
						<li><a class="dropdown-item" href="{{url_for('report.get_sale_report')}}">Sales Reports</a></li>
						<li><a class="dropdown-item" href="{{url_for('report.get_inventory_report')}}">Inventory
								Reports</a></li>
					</ul>
				</li>
				<li class="nav-item dropdown px-3">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
						data-bs-toggle="dropdown" aria-expanded="false">SETTING</a>
					<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
						<li><a class="dropdown-item" href="{{url_for('setting.get_user_management')}}">User
								Management</a></li>
						<li><a class="dropdown-item" href="{{url_for('setting.get_role_management')}}">UserRole
								Management</a></li>
						<li><a class="dropdown-item" href="{{url_for('setting.save_store_config')}}">Store
								Configuration</a></li>
					</ul>
				</li>
				<li class="nav-item px-3">
					<a class="nav-link" aria-current="page" href="{{url_for('about_us')}}">ABOUT US</a>
				</li>
			</ul>
			<div style="margin-left: 20px;">
				<a href="{{url_for('logout')}}" class="me-auto mb-2 px-3 btn btn-outline-secondary"><i
						class="fas fa-sign-out-alt"></i></a>
			</div>
		</div>
	</div>
	</div>
</nav>